"use client";

import { useCallback, useEffect, useState } from "react";

type Option={id:string;label:string};
type Row=Record<string,unknown>&{id:string};
type WorkspaceData={farms:Row[];harvests:Row[];inventory:Row[];listings:Row[];orders:Row[];crops:Option[];locations:Option[];seasons:Option[];farmsOptions:Option[];listingsOptions:Option[]};
type Field={name:string;label:string;type:"text"|"number"|"date"|"reference";required?:boolean;ref?:keyof WorkspaceData;options?:string[]};
const configs:Record<string,{label:string;fields:Field[];dataKey:keyof WorkspaceData}>={
  farms:{label:"Farm",dataKey:"farms",fields:[{name:"geography_id",label:"Location",type:"reference",required:true,ref:"locations"},{name:"cultivated_area_ha",label:"Cultivated area (hectares)",type:"number"}]},
  harvest_reports:{label:"Harvest report",dataKey:"harvests",fields:[{name:"farm_id",label:"Your farm (optional)",type:"reference",ref:"farmsOptions"},{name:"crop_id",label:"Crop",type:"reference",required:true,ref:"crops"},{name:"season_id",label:"Season (optional)",type:"reference",ref:"seasons"},{name:"geography_id",label:"Location",type:"reference",required:true,ref:"locations"},{name:"report_type",label:"Report type",type:"text",required:true,options:["intention","progress","actual"]},{name:"quantity_kg",label:"Quantity (kg)",type:"number",required:true},{name:"report_date",label:"Report date",type:"date",required:true},{name:"expected_harvest_on",label:"Expected harvest date",type:"date"},{name:"notes",label:"Notes",type:"text"}]},
  inventory_balances:{label:"Availability report",dataKey:"inventory",fields:[{name:"crop_id",label:"Crop",type:"reference",required:true,ref:"crops"},{name:"geography_id",label:"Location",type:"reference",required:true,ref:"locations"},{name:"quantity_kg",label:"Total stock (kg)",type:"number",required:true},{name:"available_kg",label:"Available stock (kg)",type:"number",required:true},{name:"as_of",label:"Date recorded",type:"date",required:true}]},
  marketplace_listings:{label:"Produce listing",dataKey:"listings",fields:[{name:"crop_id",label:"Crop",type:"reference",required:true,ref:"crops"},{name:"geography_id",label:"Pickup district / location",type:"reference",required:true,ref:"locations"},{name:"available_quantity",label:"Quantity for sale",type:"number",required:true},{name:"unit",label:"Unit",type:"text",required:true},{name:"price_per_unit",label:"Price per unit (optional)",type:"number"},{name:"currency",label:"Currency",type:"text",required:true},{name:"available_from",label:"Available from",type:"date"}]},
  marketplace_orders:{label:"Purchase request",dataKey:"orders",fields:[{name:"listing_id",label:"Verified listing",type:"reference",required:true,ref:"listingsOptions"},{name:"quantity",label:"Quantity",type:"number",required:true},{name:"agreed_price_per_unit",label:"Offer per unit (optional)",type:"number"}]},
};
const initial=(kind:string)=>Object.fromEntries(configs[kind].fields.map(f=>[f.name,f.name==="unit"?"kg":f.name==="currency"?"RWF":f.type==="reference"?"":(f.options?.[0]??"")]));
const fmt=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value).replaceAll("_"," ");

export default function MyRecordsManager({roles,initialKind,onlyKind=false}:{roles:string[];initialKind?:string;onlyKind?:boolean}){
  const allKinds=roles.includes("farmer")?["farms","harvest_reports","inventory_balances","marketplace_listings","marketplace_orders"]:["marketplace_orders"];
  const kinds=onlyKind&&initialKind&&allKinds.includes(initialKind)?[initialKind]:allKinds;
  const startKind=initialKind&&allKinds.includes(initialKind)?initialKind:kinds[0];
  const [kind,setKind]=useState(startKind);
  const [kindText,setKindText]=useState(configs[startKind].label);
  const [data,setData]=useState<WorkspaceData>({farms:[],harvests:[],inventory:[],listings:[],orders:[],crops:[],locations:[],seasons:[],farmsOptions:[],listingsOptions:[]});
  const [form,setForm]=useState<Record<string,string>>(()=>initial(startKind));
  const [editing,setEditing]=useState<Row|null>(null);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const config=configs[kind];
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/user/records",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not load your records.");setData(result);}catch(e){setError(e instanceof Error?e.message:"Could not load your records.");}finally{setLoading(false);}},[]);
  useEffect(()=>{let active=true;fetch("/api/user/records",{cache:"no-store"}).then(async response=>({response,result:await response.json()})).then(({response,result})=>{if(!active)return;if(!response.ok)throw new Error(result.error??"Could not load your records.");setData(result);setLoading(false);}).catch((e:unknown)=>{if(active){setError(e instanceof Error?e.message:"Could not load your records.");setLoading(false);}});return()=>{active=false;}},[]);
  function changeKindText(value:string){setKindText(value);const next=kinds.find(k=>configs[k].label.toLocaleLowerCase()===value.trim().toLocaleLowerCase()||k.toLocaleLowerCase()===value.trim().toLocaleLowerCase());if(next){setKind(next);setForm(initial(next));setEditing(null);setError("");setMessage("");}}
  function edit(row:Row){setEditing(row);setForm(Object.fromEntries(config.fields.map(f=>{const value=row[f.name];if(f.ref&&value!=null){const ref=data[f.ref] as Option[];return[f.name,ref.find(o=>o.id===String(value))?.label??""]}return[f.name,value==null?"":String(value).slice(0,f.type==="date"?10:undefined)]})));setMessage("");setError("");}
  function cancelEdit(){setEditing(null);setForm(initial(kind));}
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");setMessage("");try{const values:Record<string,string>={...form};for(const field of config.fields){if(field.ref&&values[field.name]?.trim()){const match=(data[field.ref] as Option[]).find(option=>option.label.toLocaleLowerCase()===values[field.name].trim().toLocaleLowerCase());if(!match)throw new Error(`${field.label} must match one of the existing values shown below the field.`);values[field.name]=match.id;}if(field.options&&values[field.name]){const match=field.options.find(option=>option.toLocaleLowerCase()===values[field.name].trim().toLocaleLowerCase());if(!match)throw new Error(`${field.label} must be ${field.options.join(", ")}.`);values[field.name]=match;}}const response=await fetch("/api/user/records",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id:editing?.id,values})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save your record.");setEditing(null);setForm(initial(kind));setMessage(editing?"Your changes were resubmitted for review.":"Your record was submitted for administrator review.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not save your record.");}finally{setSaving(false);}}
  async function remove(row:Row){if(!window.confirm("Remove this unverified record? This action is recorded."))return;await mutate({method:"DELETE",body:{kind,id:row.id},success:"Record removed."});}
  async function updateOrder(row:Row,status:string){await mutate({method:"PATCH",body:{kind:"marketplace_orders",id:row.id,status},success:`Order updated: ${status.replaceAll("_"," ")}.`});}
  async function mutate(input:{method:string;body:unknown;success:string}){setError("");setMessage("");try{const response=await fetch("/api/user/records",{method:input.method,headers:{"Content-Type":"application/json"},body:JSON.stringify(input.body)});const result=await response.json();if(!response.ok)throw new Error(result.error??"The change could not be saved.");setMessage(input.success);await load();}catch(e){setError(e instanceof Error?e.message:"The change could not be saved.");}}
  const rows=data[config.dataKey] as Row[];
  return <div className="my-records-layout">
    <section className="panel glass-panel admin-data-toolbar"><div><p className="eyebrow">YOUR ACCOUNT WORKSPACE</p><h2>{onlyKind?configs[kind].label+" records":"Your submissions and requests"}</h2><p className="panel-copy">Records belong to your account and organization. New submissions stay pending until they are reviewed.</p></div>{!onlyKind&&<label className="entity-picker">Record type<input type="text" value={kindText} onChange={e=>changeKindText(e.target.value)} placeholder="Type a record name"/><small>Type farm, harvest report, availability report, produce listing, or purchase request.</small></label>}</section>
    {roles.includes("farmer")&&(!data.crops.length||!data.locations.length)&&<p className="auth-message error setup-hint" role="status">Your administrator needs to add {!data.crops.length&&!data.locations.length?"crop and location records":!data.crops.length?"crop records":"location records"} before you can submit farms, harvests, availability, or produce listings. Your existing records remain available below.</p>}
    {kind==="marketplace_orders"&&roles.includes("buyer")&&!data.listingsOptions.length&&<p className="auth-message error setup-hint" role="status">There are no available verified listings from another seller yet. Approved listings will appear here when a farmer publishes produce.</p>}
    {(error||message)&&<p className={`auth-message ${error?"error":"success"}`} role={error?"alert":"status"}>{error||message}</p>}
    <div className="my-records-grid"><section className="panel glass-panel route-panel"><div className="panel-header"><div><p className="eyebrow">SAVED TO YOUR ACCOUNT</p><h2>{config.label}s</h2></div><button className="refresh-button" disabled={loading} onClick={()=>void load()}>↻ Refresh</button></div>
      {loading?<p className="admin-empty">Loading your data from Neon…</p>:rows.length===0?<div className="empty-state"><span className="empty-icon">▣</span><strong>No {config.label.toLowerCase()} records yet</strong><p>Use the form to add your first record.</p></div>:<div className="my-record-list">{rows.map(row=><article className="my-record-row" key={row.id}><div className="admin-record-main"><strong>{title(kind,row)}</strong><small>{detail(kind,row)}</small></div>{kind==="marketplace_orders"?<div className="my-record-actions"><span className={`badge ${String(row.status)}`}>{fmt(row.status)}</span>{orderActions(row).map(([label,status])=><button key={status} className={status==="rejected"||status==="cancelled"?"reject-button":"approve-button"} onClick={()=>void updateOrder(row,status)}>{label}</button>)}</div>:<div className="my-record-actions"><span className={`badge ${String(row.status)}`}>{fmt(row.status)}</span>{row.status!=="verified"&&<><button className="refresh-button" onClick={()=>edit(row)}>Edit</button><button className="reject-button" onClick={()=>void remove(row)}>Delete</button></>}</div>}</article>)}</div>}
      <p className="route-note">You can edit or remove submissions until they are verified. Verified data is locked for traceability.</p>
    </section>
    {kind!=="marketplace_orders"?<section className="panel glass-panel route-panel"><div className="panel-header"><div><p className="eyebrow">{editing?"EDIT SUBMISSION":"NEW SUBMISSION"}</p><h2>{editing?"Update ":"Add "}{config.label.toLowerCase()}</h2></div></div><form className="admin-data-form" onSubmit={save}>{config.fields.map(field=><Field key={field.name} field={field} value={form[field.name]??""} data={data} onChange={value=>setForm(curr=>({...curr,[field.name]:value}))}/ >)}<div className="admin-form-actions"><button className="primary-button" disabled={saving}>{saving?"Saving…":editing?"Resubmit changes":"Submit for review"}</button>{editing&&<button type="button" className="refresh-button" onClick={cancelEdit}>Cancel</button>}</div></form><p className="route-note">New submissions are marked submitted and do not affect verified summaries until an administrator approves them.</p></section>:<section className="panel glass-panel route-panel"><div className="panel-header"><div><p className="eyebrow">MARKETPLACE</p><h2>{roles.includes("buyer")?"Request a purchase":"Incoming seller requests"}</h2></div></div>{roles.includes("buyer")?<><form className="admin-data-form" onSubmit={save}>{config.fields.map(field=><Field key={field.name} field={field} value={form[field.name]??""} data={data} onChange={value=>setForm(curr=>({...curr,[field.name]:value}))}/>)}<div className="admin-form-actions"><button className="primary-button" disabled={saving||!data.listingsOptions.length}>{saving?"Sending…":"Send purchase request"}</button></div></form><p className="route-note">Requests are sent to the seller. The listing quantity is checked before the order is accepted.</p></>:<p className="panel-copy">Review buyer requests above, accept or decline them, and update accepted orders through delivery to completion.</p>}</section>}
    </div>
  </div>;
}

function Field({field,value,data,onChange}:{field:Field;value:string;data:WorkspaceData;onChange:(value:string)=>void}){const options=field.ref?data[field.ref] as Option[]:[];const matches=options.filter(o=>!value.trim()||o.label.toLocaleLowerCase().includes(value.trim().toLocaleLowerCase())).slice(0,8);return <label className="admin-data-field">{field.label}<input required={field.required} type={field.type==="reference"?"text":field.type} min={field.type==="number"?"0":undefined} step={field.type==="number"?"any":undefined} placeholder={field.type==="reference"?`Type ${field.label.toLocaleLowerCase()}`:field.options?`Type ${field.label.toLocaleLowerCase()}`:undefined} value={value} onChange={e=>onChange(e.target.value)}/>{field.ref&&<small className="field-hint">{options.length?value.trim()?`Matching records: ${matches.map(o=>o.label).join("; ")||"no match"}${matches.length===8?"; type more to narrow results":""}`:`${options.length} linked records available. Type part of a name to find a match.`:"No linked records available yet."}</small>}{field.options&&<small className="field-hint">Type one of: {field.options.join(", ")}</small>}</label>;}
function title(kind:string,row:Row){if(kind==="farms")return `Farm · ${row.district}`;if(kind==="harvest_reports")return `${row.crop} · ${row.type} · ${row.quantity} kg`;if(kind==="inventory_balances")return `${row.crop} · ${row.available} kg available`;if(kind==="marketplace_listings")return `${row.crop} · ${row.quantity} ${row.unit}`;return `${row.crop} · ${row.quantity} requested`;}
function detail(kind:string,row:Row){if(kind==="farms")return `${row.area??"Area not provided"} ha · submitted ${row.date}`;if(kind==="harvest_reports")return `${row.district} · ${row.date}`;if(kind==="inventory_balances")return `${row.district} · ${row.date}`;if(kind==="marketplace_listings")return `${row.district} · ${row.listing_status} listing`;return `${row.view_as} · ${row.other_party} · ${row.date}`;}
function orderActions(row:Row){const status=String(row.status);if(row.view_as==="buyer")return status==="requested"?[["Cancel request","cancelled"]]:[];if(status==="requested")return [["Accept","accepted"],["Decline","rejected"]];if(status==="accepted")return [["Mark in delivery","in_delivery"]];if(status==="in_delivery")return [["Complete","completed"]];return [];}
